import json
from textwrap import dedent
from typing import Union

import requests

KLEROS_TOKENS_LIST = "https://t2crtokens.eth.link/"
COINGECKO_TOKENS_LIST = "https://tokens.coingecko.com/uniswap/all.json"

TOKENS_LIST = [KLEROS_TOKENS_LIST, COINGECKO_TOKENS_LIST]

def fetch_tokens_list():
    loaded_tokens: list[dict[str, Union[str, int]]] = []

    for token_list_url in TOKENS_LIST:
        response = requests.get(token_list_url)
        tokens = json.loads(response.text)["tokens"]
        loaded_tokens.extend(tokens)

    loaded_tokens_as_string = json.dumps(loaded_tokens, indent=2)
    content = dedent(
        f"""# THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY MANUALLY, PLEASE CHECK autotx/load_tokens.py TO DO ANY MODIFICATIONS

token_list = {loaded_tokens_as_string}
"""
    )
    with open("autotx/utils/ethereum/helpers/token_list.py", "w") as f:
        f.write(content)

def run():
    fetch_tokens_list()
